message: "[LOCAL] demo config client hello world"

server:
  port: 3001

imtMessages:
  "[Caducada condicionalmente]": "mdl.generation.error.imt.caducadaCond"
  "[Caducada]": "mdl.generation.error.imt.caducada"